keys:
  - &admin_bling_hannes age1jvt938vlqcskd5f0ud0q5fpnaf6pnjxhen56ectkhf04y9guev6sg7ezsh
  - &device_vm1_hannes age1lyr2xfnv00cfra80umz0undpvmvwpaetypxkc6h6m6j6750chcxs6gw53e
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_bling_hannes
      - *device_vm1_hannes